# Generated by Django 6.1.1 on 2026-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleService_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_ID', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Vehicle_No', models.CharField(max_length=15)),
                ('Vehicle_Type', models.CharField(max_length=20)),
                ('Service_Type', models.CharField(max_length=30)),
                ('Service_Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
